# Generated by Django 4.1.1 on 2022-09-22 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_rename_price_product_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slub',
            field=models.SlugField(default='-'),
            preserve_default=False,
        ),
    ]
